# Date
date: 10072018

# Paths
newimages: /Users/arthurkoehl/ebba/new/
images: /Users/arthurkoehl/ebba/finished/

outputdir: /Users/arthurkoehl/ebba/update-10072018/
keypoints: /Users/arthurkoehl/ebba/keypoints/10072018/
matches: /Users/arthurkoehl/ebba/matches/10072018/

# SURF Parameters
minHessian: 3000
octaves: 8
octaveLayers: 8
min Size: 65 
min Resp: 500.0

scale: 1
ratio: .75
