# Date
date: 28102018

# Paths
newimages: /data2/dsl/ballads/new/
images: /data2/dsl/ballads/Finished-Images/

outputdir: /data2/dsl/ballads/update-28102018/
keypoints: /data2/dsl/ballads/Keypoints/28102018/
matches: /data2/dsl/ballads/Matches/28102018/

# SURF Parameters
minHessian: 3000
octaves: 8
octaveLayers: 8
min Size: 65 
min Resp: 500.0

scale: 1
ratio: .75
